// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: api/nap/v1/ai.proto

package napv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IntentResolutionService_ResolveIntent_FullMethodName      = "/nupi.nap.v1.IntentResolutionService/ResolveIntent"
	IntentResolutionService_GetCapabilities_FullMethodName    = "/nupi.nap.v1.IntentResolutionService/GetCapabilities"
	IntentResolutionService_GenerateEmbeddings_FullMethodName = "/nupi.nap.v1.IntentResolutionService/GenerateEmbeddings"
)

// IntentResolutionServiceClient is the client API for IntentResolutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntentResolutionServiceClient interface {
	// ResolveIntent processes user input and returns intended action(s).
	ResolveIntent(ctx context.Context, in *ResolveIntentRequest, opts ...grpc.CallOption) (*ResolveIntentResponse, error)
	// GetCapabilities returns the adapter's supported features and version info.
	// Adapters that do not implement this RPC will return UNIMPLEMENTED, which
	// callers should treat as "capabilities unknown" and proceed normally.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// GenerateEmbeddings produces vector embeddings for the given texts.
	// Used by the awareness system for semantic search indexing and queries.
	GenerateEmbeddings(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type intentResolutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentResolutionServiceClient(cc grpc.ClientConnInterface) IntentResolutionServiceClient {
	return &intentResolutionServiceClient{cc}
}

func (c *intentResolutionServiceClient) ResolveIntent(ctx context.Context, in *ResolveIntentRequest, opts ...grpc.CallOption) (*ResolveIntentResponse, error) {
	out := new(ResolveIntentResponse)
	err := c.cc.Invoke(ctx, IntentResolutionService_ResolveIntent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentResolutionServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, IntentResolutionService_GetCapabilities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentResolutionServiceClient) GenerateEmbeddings(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, IntentResolutionService_GenerateEmbeddings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentResolutionServiceServer is the server API for IntentResolutionService service.
// All implementations must embed UnimplementedIntentResolutionServiceServer
// for forward compatibility
type IntentResolutionServiceServer interface {
	// ResolveIntent processes user input and returns intended action(s).
	ResolveIntent(context.Context, *ResolveIntentRequest) (*ResolveIntentResponse, error)
	// GetCapabilities returns the adapter's supported features and version info.
	// Adapters that do not implement this RPC will return UNIMPLEMENTED, which
	// callers should treat as "capabilities unknown" and proceed normally.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	// GenerateEmbeddings produces vector embeddings for the given texts.
	// Used by the awareness system for semantic search indexing and queries.
	GenerateEmbeddings(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedIntentResolutionServiceServer()
}

// UnimplementedIntentResolutionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntentResolutionServiceServer struct {
}

func (UnimplementedIntentResolutionServiceServer) ResolveIntent(context.Context, *ResolveIntentRequest) (*ResolveIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveIntent not implemented")
}
func (UnimplementedIntentResolutionServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedIntentResolutionServiceServer) GenerateEmbeddings(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEmbeddings not implemented")
}
func (UnimplementedIntentResolutionServiceServer) mustEmbedUnimplementedIntentResolutionServiceServer() {
}

// UnsafeIntentResolutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentResolutionServiceServer will
// result in compilation errors.
type UnsafeIntentResolutionServiceServer interface {
	mustEmbedUnimplementedIntentResolutionServiceServer()
}

func RegisterIntentResolutionServiceServer(s grpc.ServiceRegistrar, srv IntentResolutionServiceServer) {
	s.RegisterService(&IntentResolutionService_ServiceDesc, srv)
}

func _IntentResolutionService_ResolveIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentResolutionServiceServer).ResolveIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentResolutionService_ResolveIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentResolutionServiceServer).ResolveIntent(ctx, req.(*ResolveIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentResolutionService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentResolutionServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentResolutionService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentResolutionServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentResolutionService_GenerateEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentResolutionServiceServer).GenerateEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentResolutionService_GenerateEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentResolutionServiceServer).GenerateEmbeddings(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntentResolutionService_ServiceDesc is the grpc.ServiceDesc for IntentResolutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentResolutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.nap.v1.IntentResolutionService",
	HandlerType: (*IntentResolutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveIntent",
			Handler:    _IntentResolutionService_ResolveIntent_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _IntentResolutionService_GetCapabilities_Handler,
		},
		{
			MethodName: "GenerateEmbeddings",
			Handler:    _IntentResolutionService_GenerateEmbeddings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nap/v1/ai.proto",
}
