// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: api/nap/v1/tts.proto

package napv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TextToSpeechService_StreamSynthesis_FullMethodName = "/nupi.nap.v1.TextToSpeechService/StreamSynthesis"
)

// TextToSpeechServiceClient is the client API for TextToSpeechService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextToSpeechServiceClient interface {
	StreamSynthesis(ctx context.Context, in *StreamSynthesisRequest, opts ...grpc.CallOption) (TextToSpeechService_StreamSynthesisClient, error)
}

type textToSpeechServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextToSpeechServiceClient(cc grpc.ClientConnInterface) TextToSpeechServiceClient {
	return &textToSpeechServiceClient{cc}
}

func (c *textToSpeechServiceClient) StreamSynthesis(ctx context.Context, in *StreamSynthesisRequest, opts ...grpc.CallOption) (TextToSpeechService_StreamSynthesisClient, error) {
	stream, err := c.cc.NewStream(ctx, &TextToSpeechService_ServiceDesc.Streams[0], TextToSpeechService_StreamSynthesis_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &textToSpeechServiceStreamSynthesisClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TextToSpeechService_StreamSynthesisClient interface {
	Recv() (*SynthesisResponse, error)
	grpc.ClientStream
}

type textToSpeechServiceStreamSynthesisClient struct {
	grpc.ClientStream
}

func (x *textToSpeechServiceStreamSynthesisClient) Recv() (*SynthesisResponse, error) {
	m := new(SynthesisResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TextToSpeechServiceServer is the server API for TextToSpeechService service.
// All implementations must embed UnimplementedTextToSpeechServiceServer
// for forward compatibility
type TextToSpeechServiceServer interface {
	StreamSynthesis(*StreamSynthesisRequest, TextToSpeechService_StreamSynthesisServer) error
	mustEmbedUnimplementedTextToSpeechServiceServer()
}

// UnimplementedTextToSpeechServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTextToSpeechServiceServer struct {
}

func (UnimplementedTextToSpeechServiceServer) StreamSynthesis(*StreamSynthesisRequest, TextToSpeechService_StreamSynthesisServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSynthesis not implemented")
}
func (UnimplementedTextToSpeechServiceServer) mustEmbedUnimplementedTextToSpeechServiceServer() {}

// UnsafeTextToSpeechServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextToSpeechServiceServer will
// result in compilation errors.
type UnsafeTextToSpeechServiceServer interface {
	mustEmbedUnimplementedTextToSpeechServiceServer()
}

func RegisterTextToSpeechServiceServer(s grpc.ServiceRegistrar, srv TextToSpeechServiceServer) {
	s.RegisterService(&TextToSpeechService_ServiceDesc, srv)
}

func _TextToSpeechService_StreamSynthesis_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSynthesisRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TextToSpeechServiceServer).StreamSynthesis(m, &textToSpeechServiceStreamSynthesisServer{stream})
}

type TextToSpeechService_StreamSynthesisServer interface {
	Send(*SynthesisResponse) error
	grpc.ServerStream
}

type textToSpeechServiceStreamSynthesisServer struct {
	grpc.ServerStream
}

func (x *textToSpeechServiceStreamSynthesisServer) Send(m *SynthesisResponse) error {
	return x.ServerStream.SendMsg(m)
}

// TextToSpeechService_ServiceDesc is the grpc.ServiceDesc for TextToSpeechService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextToSpeechService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.nap.v1.TextToSpeechService",
	HandlerType: (*TextToSpeechServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSynthesis",
			Handler:       _TextToSpeechService_StreamSynthesis_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/nap/v1/tts.proto",
}
