// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: nap/v1/vad.proto

package napv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VoiceActivityDetectionService_DetectSpeech_FullMethodName = "/nupi.nap.v1.VoiceActivityDetectionService/DetectSpeech"
)

// VoiceActivityDetectionServiceClient is the client API for VoiceActivityDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceActivityDetectionServiceClient interface {
	DetectSpeech(ctx context.Context, opts ...grpc.CallOption) (VoiceActivityDetectionService_DetectSpeechClient, error)
}

type voiceActivityDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceActivityDetectionServiceClient(cc grpc.ClientConnInterface) VoiceActivityDetectionServiceClient {
	return &voiceActivityDetectionServiceClient{cc}
}

func (c *voiceActivityDetectionServiceClient) DetectSpeech(ctx context.Context, opts ...grpc.CallOption) (VoiceActivityDetectionService_DetectSpeechClient, error) {
	stream, err := c.cc.NewStream(ctx, &VoiceActivityDetectionService_ServiceDesc.Streams[0], VoiceActivityDetectionService_DetectSpeech_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &voiceActivityDetectionServiceDetectSpeechClient{stream}
	return x, nil
}

type VoiceActivityDetectionService_DetectSpeechClient interface {
	Send(*DetectSpeechRequest) error
	Recv() (*SpeechEvent, error)
	grpc.ClientStream
}

type voiceActivityDetectionServiceDetectSpeechClient struct {
	grpc.ClientStream
}

func (x *voiceActivityDetectionServiceDetectSpeechClient) Send(m *DetectSpeechRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *voiceActivityDetectionServiceDetectSpeechClient) Recv() (*SpeechEvent, error) {
	m := new(SpeechEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VoiceActivityDetectionServiceServer is the server API for VoiceActivityDetectionService service.
// All implementations must embed UnimplementedVoiceActivityDetectionServiceServer
// for forward compatibility
type VoiceActivityDetectionServiceServer interface {
	DetectSpeech(VoiceActivityDetectionService_DetectSpeechServer) error
	mustEmbedUnimplementedVoiceActivityDetectionServiceServer()
}

// UnimplementedVoiceActivityDetectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoiceActivityDetectionServiceServer struct {
}

func (UnimplementedVoiceActivityDetectionServiceServer) DetectSpeech(VoiceActivityDetectionService_DetectSpeechServer) error {
	return status.Errorf(codes.Unimplemented, "method DetectSpeech not implemented")
}
func (UnimplementedVoiceActivityDetectionServiceServer) mustEmbedUnimplementedVoiceActivityDetectionServiceServer() {
}

// UnsafeVoiceActivityDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceActivityDetectionServiceServer will
// result in compilation errors.
type UnsafeVoiceActivityDetectionServiceServer interface {
	mustEmbedUnimplementedVoiceActivityDetectionServiceServer()
}

func RegisterVoiceActivityDetectionServiceServer(s grpc.ServiceRegistrar, srv VoiceActivityDetectionServiceServer) {
	s.RegisterService(&VoiceActivityDetectionService_ServiceDesc, srv)
}

func _VoiceActivityDetectionService_DetectSpeech_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceActivityDetectionServiceServer).DetectSpeech(&voiceActivityDetectionServiceDetectSpeechServer{stream})
}

type VoiceActivityDetectionService_DetectSpeechServer interface {
	Send(*SpeechEvent) error
	Recv() (*DetectSpeechRequest, error)
	grpc.ServerStream
}

type voiceActivityDetectionServiceDetectSpeechServer struct {
	grpc.ServerStream
}

func (x *voiceActivityDetectionServiceDetectSpeechServer) Send(m *SpeechEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *voiceActivityDetectionServiceDetectSpeechServer) Recv() (*DetectSpeechRequest, error) {
	m := new(DetectSpeechRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VoiceActivityDetectionService_ServiceDesc is the grpc.ServiceDesc for VoiceActivityDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceActivityDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.nap.v1.VoiceActivityDetectionService",
	HandlerType: (*VoiceActivityDetectionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectSpeech",
			Handler:       _VoiceActivityDetectionService_DetectSpeech_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nap/v1/vad.proto",
}
