// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: nupi.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DaemonService_Status_FullMethodName            = "/nupi.api.v1.DaemonService/Status"
	DaemonService_Shutdown_FullMethodName          = "/nupi.api.v1.DaemonService/Shutdown"
	DaemonService_GetPluginWarnings_FullMethodName = "/nupi.api.v1.DaemonService/GetPluginWarnings"
	DaemonService_ListLanguages_FullMethodName     = "/nupi.api.v1.DaemonService/ListLanguages"
	DaemonService_ReloadPlugins_FullMethodName     = "/nupi.api.v1.DaemonService/ReloadPlugins"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	Status(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatusResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	GetPluginWarnings(ctx context.Context, in *GetPluginWarningsRequest, opts ...grpc.CallOption) (*GetPluginWarningsResponse, error)
	ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error)
	ReloadPlugins(ctx context.Context, in *ReloadPluginsRequest, opts ...grpc.CallOption) (*ReloadPluginsResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Status(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatusResponse, error) {
	out := new(DaemonStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, DaemonService_Shutdown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetPluginWarnings(ctx context.Context, in *GetPluginWarningsRequest, opts ...grpc.CallOption) (*GetPluginWarningsResponse, error) {
	out := new(GetPluginWarningsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetPluginWarnings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error) {
	out := new(ListLanguagesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListLanguages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReloadPlugins(ctx context.Context, in *ReloadPluginsRequest, opts ...grpc.CallOption) (*ReloadPluginsResponse, error) {
	out := new(ReloadPluginsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ReloadPlugins_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility
type DaemonServiceServer interface {
	Status(context.Context, *DaemonStatusRequest) (*DaemonStatusResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	GetPluginWarnings(context.Context, *GetPluginWarningsRequest) (*GetPluginWarningsResponse, error)
	ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error)
	ReloadPlugins(context.Context, *ReloadPluginsRequest) (*ReloadPluginsResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDaemonServiceServer struct {
}

func (UnimplementedDaemonServiceServer) Status(context.Context, *DaemonStatusRequest) (*DaemonStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDaemonServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServiceServer) GetPluginWarnings(context.Context, *GetPluginWarningsRequest) (*GetPluginWarningsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginWarnings not implemented")
}
func (UnimplementedDaemonServiceServer) ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLanguages not implemented")
}
func (UnimplementedDaemonServiceServer) ReloadPlugins(context.Context, *ReloadPluginsRequest) (*ReloadPluginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPlugins not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Status(ctx, req.(*DaemonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetPluginWarnings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginWarningsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetPluginWarnings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetPluginWarnings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetPluginWarnings(ctx, req.(*GetPluginWarningsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListLanguages(ctx, req.(*ListLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReloadPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReloadPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReloadPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReloadPlugins(ctx, req.(*ReloadPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _DaemonService_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DaemonService_Shutdown_Handler,
		},
		{
			MethodName: "GetPluginWarnings",
			Handler:    _DaemonService_GetPluginWarnings_Handler,
		},
		{
			MethodName: "ListLanguages",
			Handler:    _DaemonService_ListLanguages_Handler,
		},
		{
			MethodName: "ReloadPlugins",
			Handler:    _DaemonService_ReloadPlugins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nupi.proto",
}

const (
	SessionsService_ListSessions_FullMethodName          = "/nupi.api.v1.SessionsService/ListSessions"
	SessionsService_CreateSession_FullMethodName         = "/nupi.api.v1.SessionsService/CreateSession"
	SessionsService_GetSession_FullMethodName            = "/nupi.api.v1.SessionsService/GetSession"
	SessionsService_KillSession_FullMethodName           = "/nupi.api.v1.SessionsService/KillSession"
	SessionsService_SendInput_FullMethodName             = "/nupi.api.v1.SessionsService/SendInput"
	SessionsService_AttachSession_FullMethodName         = "/nupi.api.v1.SessionsService/AttachSession"
	SessionsService_GetSessionMode_FullMethodName        = "/nupi.api.v1.SessionsService/GetSessionMode"
	SessionsService_SetSessionMode_FullMethodName        = "/nupi.api.v1.SessionsService/SetSessionMode"
	SessionsService_GetConversation_FullMethodName       = "/nupi.api.v1.SessionsService/GetConversation"
	SessionsService_GetGlobalConversation_FullMethodName = "/nupi.api.v1.SessionsService/GetGlobalConversation"
	SessionsService_SendVoiceCommand_FullMethodName      = "/nupi.api.v1.SessionsService/SendVoiceCommand"
)

// SessionsServiceClient is the client API for SessionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionsServiceClient interface {
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*KillSessionResponse, error)
	SendInput(ctx context.Context, in *SendInputRequest, opts ...grpc.CallOption) (*SendInputResponse, error)
	AttachSession(ctx context.Context, opts ...grpc.CallOption) (SessionsService_AttachSessionClient, error)
	GetSessionMode(ctx context.Context, in *GetSessionModeRequest, opts ...grpc.CallOption) (*GetSessionModeResponse, error)
	SetSessionMode(ctx context.Context, in *SetSessionModeRequest, opts ...grpc.CallOption) (*SetSessionModeResponse, error)
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
	GetGlobalConversation(ctx context.Context, in *GetGlobalConversationRequest, opts ...grpc.CallOption) (*GetGlobalConversationResponse, error)
	SendVoiceCommand(ctx context.Context, in *SendVoiceCommandRequest, opts ...grpc.CallOption) (*SendVoiceCommandResponse, error)
}

type sessionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsServiceClient(cc grpc.ClientConnInterface) SessionsServiceClient {
	return &sessionsServiceClient{cc}
}

func (c *sessionsServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionsService_ListSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SessionsService_CreateSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, SessionsService_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*KillSessionResponse, error) {
	out := new(KillSessionResponse)
	err := c.cc.Invoke(ctx, SessionsService_KillSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) SendInput(ctx context.Context, in *SendInputRequest, opts ...grpc.CallOption) (*SendInputResponse, error) {
	out := new(SendInputResponse)
	err := c.cc.Invoke(ctx, SessionsService_SendInput_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) AttachSession(ctx context.Context, opts ...grpc.CallOption) (SessionsService_AttachSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &SessionsService_ServiceDesc.Streams[0], SessionsService_AttachSession_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionsServiceAttachSessionClient{stream}
	return x, nil
}

type SessionsService_AttachSessionClient interface {
	Send(*AttachSessionRequest) error
	Recv() (*AttachSessionResponse, error)
	grpc.ClientStream
}

type sessionsServiceAttachSessionClient struct {
	grpc.ClientStream
}

func (x *sessionsServiceAttachSessionClient) Send(m *AttachSessionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sessionsServiceAttachSessionClient) Recv() (*AttachSessionResponse, error) {
	m := new(AttachSessionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionsServiceClient) GetSessionMode(ctx context.Context, in *GetSessionModeRequest, opts ...grpc.CallOption) (*GetSessionModeResponse, error) {
	out := new(GetSessionModeResponse)
	err := c.cc.Invoke(ctx, SessionsService_GetSessionMode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) SetSessionMode(ctx context.Context, in *SetSessionModeRequest, opts ...grpc.CallOption) (*SetSessionModeResponse, error) {
	out := new(SetSessionModeResponse)
	err := c.cc.Invoke(ctx, SessionsService_SetSessionMode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	out := new(GetConversationResponse)
	err := c.cc.Invoke(ctx, SessionsService_GetConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) GetGlobalConversation(ctx context.Context, in *GetGlobalConversationRequest, opts ...grpc.CallOption) (*GetGlobalConversationResponse, error) {
	out := new(GetGlobalConversationResponse)
	err := c.cc.Invoke(ctx, SessionsService_GetGlobalConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsServiceClient) SendVoiceCommand(ctx context.Context, in *SendVoiceCommandRequest, opts ...grpc.CallOption) (*SendVoiceCommandResponse, error) {
	out := new(SendVoiceCommandResponse)
	err := c.cc.Invoke(ctx, SessionsService_SendVoiceCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServiceServer is the server API for SessionsService service.
// All implementations must embed UnimplementedSessionsServiceServer
// for forward compatibility
type SessionsServiceServer interface {
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	KillSession(context.Context, *KillSessionRequest) (*KillSessionResponse, error)
	SendInput(context.Context, *SendInputRequest) (*SendInputResponse, error)
	AttachSession(SessionsService_AttachSessionServer) error
	GetSessionMode(context.Context, *GetSessionModeRequest) (*GetSessionModeResponse, error)
	SetSessionMode(context.Context, *SetSessionModeRequest) (*SetSessionModeResponse, error)
	GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error)
	GetGlobalConversation(context.Context, *GetGlobalConversationRequest) (*GetGlobalConversationResponse, error)
	SendVoiceCommand(context.Context, *SendVoiceCommandRequest) (*SendVoiceCommandResponse, error)
	mustEmbedUnimplementedSessionsServiceServer()
}

// UnimplementedSessionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSessionsServiceServer struct {
}

func (UnimplementedSessionsServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionsServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionsServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionsServiceServer) KillSession(context.Context, *KillSessionRequest) (*KillSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillSession not implemented")
}
func (UnimplementedSessionsServiceServer) SendInput(context.Context, *SendInputRequest) (*SendInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInput not implemented")
}
func (UnimplementedSessionsServiceServer) AttachSession(SessionsService_AttachSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method AttachSession not implemented")
}
func (UnimplementedSessionsServiceServer) GetSessionMode(context.Context, *GetSessionModeRequest) (*GetSessionModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionMode not implemented")
}
func (UnimplementedSessionsServiceServer) SetSessionMode(context.Context, *SetSessionModeRequest) (*SetSessionModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSessionMode not implemented")
}
func (UnimplementedSessionsServiceServer) GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedSessionsServiceServer) GetGlobalConversation(context.Context, *GetGlobalConversationRequest) (*GetGlobalConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalConversation not implemented")
}
func (UnimplementedSessionsServiceServer) SendVoiceCommand(context.Context, *SendVoiceCommandRequest) (*SendVoiceCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVoiceCommand not implemented")
}
func (UnimplementedSessionsServiceServer) mustEmbedUnimplementedSessionsServiceServer() {}

// UnsafeSessionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServiceServer will
// result in compilation errors.
type UnsafeSessionsServiceServer interface {
	mustEmbedUnimplementedSessionsServiceServer()
}

func RegisterSessionsServiceServer(s grpc.ServiceRegistrar, srv SessionsServiceServer) {
	s.RegisterService(&SessionsService_ServiceDesc, srv)
}

func _SessionsService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_KillSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).KillSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_KillSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).KillSession(ctx, req.(*KillSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_SendInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).SendInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_SendInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).SendInput(ctx, req.(*SendInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_AttachSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionsServiceServer).AttachSession(&sessionsServiceAttachSessionServer{stream})
}

type SessionsService_AttachSessionServer interface {
	Send(*AttachSessionResponse) error
	Recv() (*AttachSessionRequest, error)
	grpc.ServerStream
}

type sessionsServiceAttachSessionServer struct {
	grpc.ServerStream
}

func (x *sessionsServiceAttachSessionServer) Send(m *AttachSessionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sessionsServiceAttachSessionServer) Recv() (*AttachSessionRequest, error) {
	m := new(AttachSessionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SessionsService_GetSessionMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetSessionMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetSessionMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetSessionMode(ctx, req.(*GetSessionModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_SetSessionMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSessionModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).SetSessionMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_SetSessionMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).SetSessionMode(ctx, req.(*SetSessionModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_GetGlobalConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).GetGlobalConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_GetGlobalConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).GetGlobalConversation(ctx, req.(*GetGlobalConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionsService_SendVoiceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVoiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServiceServer).SendVoiceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionsService_SendVoiceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServiceServer).SendVoiceCommand(ctx, req.(*SendVoiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionsService_ServiceDesc is the grpc.ServiceDesc for SessionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.SessionsService",
	HandlerType: (*SessionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _SessionsService_ListSessions_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _SessionsService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionsService_GetSession_Handler,
		},
		{
			MethodName: "KillSession",
			Handler:    _SessionsService_KillSession_Handler,
		},
		{
			MethodName: "SendInput",
			Handler:    _SessionsService_SendInput_Handler,
		},
		{
			MethodName: "GetSessionMode",
			Handler:    _SessionsService_GetSessionMode_Handler,
		},
		{
			MethodName: "SetSessionMode",
			Handler:    _SessionsService_SetSessionMode_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _SessionsService_GetConversation_Handler,
		},
		{
			MethodName: "GetGlobalConversation",
			Handler:    _SessionsService_GetGlobalConversation_Handler,
		},
		{
			MethodName: "SendVoiceCommand",
			Handler:    _SessionsService_SendVoiceCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachSession",
			Handler:       _SessionsService_AttachSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nupi.proto",
}

const (
	AdapterRuntimeService_Overview_FullMethodName          = "/nupi.api.v1.AdapterRuntimeService/Overview"
	AdapterRuntimeService_BindAdapter_FullMethodName       = "/nupi.api.v1.AdapterRuntimeService/BindAdapter"
	AdapterRuntimeService_StartAdapter_FullMethodName      = "/nupi.api.v1.AdapterRuntimeService/StartAdapter"
	AdapterRuntimeService_StopAdapter_FullMethodName       = "/nupi.api.v1.AdapterRuntimeService/StopAdapter"
	AdapterRuntimeService_RegisterAdapter_FullMethodName   = "/nupi.api.v1.AdapterRuntimeService/RegisterAdapter"
	AdapterRuntimeService_StreamAdapterLogs_FullMethodName = "/nupi.api.v1.AdapterRuntimeService/StreamAdapterLogs"
	AdapterRuntimeService_GetAdapterLogs_FullMethodName    = "/nupi.api.v1.AdapterRuntimeService/GetAdapterLogs"
)

// AdapterRuntimeServiceClient is the client API for AdapterRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterRuntimeServiceClient interface {
	Overview(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdaptersOverviewResponse, error)
	BindAdapter(ctx context.Context, in *BindAdapterRequest, opts ...grpc.CallOption) (*AdapterActionResponse, error)
	StartAdapter(ctx context.Context, in *AdapterSlotRequest, opts ...grpc.CallOption) (*AdapterActionResponse, error)
	StopAdapter(ctx context.Context, in *AdapterSlotRequest, opts ...grpc.CallOption) (*AdapterActionResponse, error)
	RegisterAdapter(ctx context.Context, in *RegisterAdapterRequest, opts ...grpc.CallOption) (*RegisterAdapterResponse, error)
	StreamAdapterLogs(ctx context.Context, in *StreamAdapterLogsRequest, opts ...grpc.CallOption) (AdapterRuntimeService_StreamAdapterLogsClient, error)
	GetAdapterLogs(ctx context.Context, in *GetAdapterLogsRequest, opts ...grpc.CallOption) (*GetAdapterLogsResponse, error)
}

type adapterRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterRuntimeServiceClient(cc grpc.ClientConnInterface) AdapterRuntimeServiceClient {
	return &adapterRuntimeServiceClient{cc}
}

func (c *adapterRuntimeServiceClient) Overview(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdaptersOverviewResponse, error) {
	out := new(AdaptersOverviewResponse)
	err := c.cc.Invoke(ctx, AdapterRuntimeService_Overview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterRuntimeServiceClient) BindAdapter(ctx context.Context, in *BindAdapterRequest, opts ...grpc.CallOption) (*AdapterActionResponse, error) {
	out := new(AdapterActionResponse)
	err := c.cc.Invoke(ctx, AdapterRuntimeService_BindAdapter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterRuntimeServiceClient) StartAdapter(ctx context.Context, in *AdapterSlotRequest, opts ...grpc.CallOption) (*AdapterActionResponse, error) {
	out := new(AdapterActionResponse)
	err := c.cc.Invoke(ctx, AdapterRuntimeService_StartAdapter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterRuntimeServiceClient) StopAdapter(ctx context.Context, in *AdapterSlotRequest, opts ...grpc.CallOption) (*AdapterActionResponse, error) {
	out := new(AdapterActionResponse)
	err := c.cc.Invoke(ctx, AdapterRuntimeService_StopAdapter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterRuntimeServiceClient) RegisterAdapter(ctx context.Context, in *RegisterAdapterRequest, opts ...grpc.CallOption) (*RegisterAdapterResponse, error) {
	out := new(RegisterAdapterResponse)
	err := c.cc.Invoke(ctx, AdapterRuntimeService_RegisterAdapter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterRuntimeServiceClient) StreamAdapterLogs(ctx context.Context, in *StreamAdapterLogsRequest, opts ...grpc.CallOption) (AdapterRuntimeService_StreamAdapterLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AdapterRuntimeService_ServiceDesc.Streams[0], AdapterRuntimeService_StreamAdapterLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &adapterRuntimeServiceStreamAdapterLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdapterRuntimeService_StreamAdapterLogsClient interface {
	Recv() (*AdapterLogStreamEntry, error)
	grpc.ClientStream
}

type adapterRuntimeServiceStreamAdapterLogsClient struct {
	grpc.ClientStream
}

func (x *adapterRuntimeServiceStreamAdapterLogsClient) Recv() (*AdapterLogStreamEntry, error) {
	m := new(AdapterLogStreamEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adapterRuntimeServiceClient) GetAdapterLogs(ctx context.Context, in *GetAdapterLogsRequest, opts ...grpc.CallOption) (*GetAdapterLogsResponse, error) {
	out := new(GetAdapterLogsResponse)
	err := c.cc.Invoke(ctx, AdapterRuntimeService_GetAdapterLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterRuntimeServiceServer is the server API for AdapterRuntimeService service.
// All implementations must embed UnimplementedAdapterRuntimeServiceServer
// for forward compatibility
type AdapterRuntimeServiceServer interface {
	Overview(context.Context, *emptypb.Empty) (*AdaptersOverviewResponse, error)
	BindAdapter(context.Context, *BindAdapterRequest) (*AdapterActionResponse, error)
	StartAdapter(context.Context, *AdapterSlotRequest) (*AdapterActionResponse, error)
	StopAdapter(context.Context, *AdapterSlotRequest) (*AdapterActionResponse, error)
	RegisterAdapter(context.Context, *RegisterAdapterRequest) (*RegisterAdapterResponse, error)
	StreamAdapterLogs(*StreamAdapterLogsRequest, AdapterRuntimeService_StreamAdapterLogsServer) error
	GetAdapterLogs(context.Context, *GetAdapterLogsRequest) (*GetAdapterLogsResponse, error)
	mustEmbedUnimplementedAdapterRuntimeServiceServer()
}

// UnimplementedAdapterRuntimeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdapterRuntimeServiceServer struct {
}

func (UnimplementedAdapterRuntimeServiceServer) Overview(context.Context, *emptypb.Empty) (*AdaptersOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Overview not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) BindAdapter(context.Context, *BindAdapterRequest) (*AdapterActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindAdapter not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) StartAdapter(context.Context, *AdapterSlotRequest) (*AdapterActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAdapter not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) StopAdapter(context.Context, *AdapterSlotRequest) (*AdapterActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAdapter not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) RegisterAdapter(context.Context, *RegisterAdapterRequest) (*RegisterAdapterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAdapter not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) StreamAdapterLogs(*StreamAdapterLogsRequest, AdapterRuntimeService_StreamAdapterLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAdapterLogs not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) GetAdapterLogs(context.Context, *GetAdapterLogsRequest) (*GetAdapterLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdapterLogs not implemented")
}
func (UnimplementedAdapterRuntimeServiceServer) mustEmbedUnimplementedAdapterRuntimeServiceServer() {}

// UnsafeAdapterRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterRuntimeServiceServer will
// result in compilation errors.
type UnsafeAdapterRuntimeServiceServer interface {
	mustEmbedUnimplementedAdapterRuntimeServiceServer()
}

func RegisterAdapterRuntimeServiceServer(s grpc.ServiceRegistrar, srv AdapterRuntimeServiceServer) {
	s.RegisterService(&AdapterRuntimeService_ServiceDesc, srv)
}

func _AdapterRuntimeService_Overview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterRuntimeServiceServer).Overview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterRuntimeService_Overview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterRuntimeServiceServer).Overview(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterRuntimeService_BindAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterRuntimeServiceServer).BindAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterRuntimeService_BindAdapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterRuntimeServiceServer).BindAdapter(ctx, req.(*BindAdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterRuntimeService_StartAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterRuntimeServiceServer).StartAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterRuntimeService_StartAdapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterRuntimeServiceServer).StartAdapter(ctx, req.(*AdapterSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterRuntimeService_StopAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterRuntimeServiceServer).StopAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterRuntimeService_StopAdapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterRuntimeServiceServer).StopAdapter(ctx, req.(*AdapterSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterRuntimeService_RegisterAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterRuntimeServiceServer).RegisterAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterRuntimeService_RegisterAdapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterRuntimeServiceServer).RegisterAdapter(ctx, req.(*RegisterAdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterRuntimeService_StreamAdapterLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAdapterLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdapterRuntimeServiceServer).StreamAdapterLogs(m, &adapterRuntimeServiceStreamAdapterLogsServer{stream})
}

type AdapterRuntimeService_StreamAdapterLogsServer interface {
	Send(*AdapterLogStreamEntry) error
	grpc.ServerStream
}

type adapterRuntimeServiceStreamAdapterLogsServer struct {
	grpc.ServerStream
}

func (x *adapterRuntimeServiceStreamAdapterLogsServer) Send(m *AdapterLogStreamEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _AdapterRuntimeService_GetAdapterLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdapterLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterRuntimeServiceServer).GetAdapterLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterRuntimeService_GetAdapterLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterRuntimeServiceServer).GetAdapterLogs(ctx, req.(*GetAdapterLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterRuntimeService_ServiceDesc is the grpc.ServiceDesc for AdapterRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.AdapterRuntimeService",
	HandlerType: (*AdapterRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Overview",
			Handler:    _AdapterRuntimeService_Overview_Handler,
		},
		{
			MethodName: "BindAdapter",
			Handler:    _AdapterRuntimeService_BindAdapter_Handler,
		},
		{
			MethodName: "StartAdapter",
			Handler:    _AdapterRuntimeService_StartAdapter_Handler,
		},
		{
			MethodName: "StopAdapter",
			Handler:    _AdapterRuntimeService_StopAdapter_Handler,
		},
		{
			MethodName: "RegisterAdapter",
			Handler:    _AdapterRuntimeService_RegisterAdapter_Handler,
		},
		{
			MethodName: "GetAdapterLogs",
			Handler:    _AdapterRuntimeService_GetAdapterLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAdapterLogs",
			Handler:       _AdapterRuntimeService_StreamAdapterLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nupi.proto",
}

const (
	AudioService_StreamAudioIn_FullMethodName        = "/nupi.api.v1.AudioService/StreamAudioIn"
	AudioService_StreamAudioOut_FullMethodName       = "/nupi.api.v1.AudioService/StreamAudioOut"
	AudioService_InterruptTTS_FullMethodName         = "/nupi.api.v1.AudioService/InterruptTTS"
	AudioService_GetAudioCapabilities_FullMethodName = "/nupi.api.v1.AudioService/GetAudioCapabilities"
)

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	StreamAudioIn(ctx context.Context, opts ...grpc.CallOption) (AudioService_StreamAudioInClient, error)
	StreamAudioOut(ctx context.Context, in *StreamAudioOutRequest, opts ...grpc.CallOption) (AudioService_StreamAudioOutClient, error)
	InterruptTTS(ctx context.Context, in *InterruptTTSRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAudioCapabilities(ctx context.Context, in *GetAudioCapabilitiesRequest, opts ...grpc.CallOption) (*GetAudioCapabilitiesResponse, error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) StreamAudioIn(ctx context.Context, opts ...grpc.CallOption) (AudioService_StreamAudioInClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], AudioService_StreamAudioIn_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &audioServiceStreamAudioInClient{stream}
	return x, nil
}

type AudioService_StreamAudioInClient interface {
	Send(*StreamAudioInRequest) error
	CloseAndRecv() (*StreamAudioInResponse, error)
	grpc.ClientStream
}

type audioServiceStreamAudioInClient struct {
	grpc.ClientStream
}

func (x *audioServiceStreamAudioInClient) Send(m *StreamAudioInRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *audioServiceStreamAudioInClient) CloseAndRecv() (*StreamAudioInResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamAudioInResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *audioServiceClient) StreamAudioOut(ctx context.Context, in *StreamAudioOutRequest, opts ...grpc.CallOption) (AudioService_StreamAudioOutClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[1], AudioService_StreamAudioOut_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &audioServiceStreamAudioOutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AudioService_StreamAudioOutClient interface {
	Recv() (*StreamAudioOutResponse, error)
	grpc.ClientStream
}

type audioServiceStreamAudioOutClient struct {
	grpc.ClientStream
}

func (x *audioServiceStreamAudioOutClient) Recv() (*StreamAudioOutResponse, error) {
	m := new(StreamAudioOutResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *audioServiceClient) InterruptTTS(ctx context.Context, in *InterruptTTSRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AudioService_InterruptTTS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) GetAudioCapabilities(ctx context.Context, in *GetAudioCapabilitiesRequest, opts ...grpc.CallOption) (*GetAudioCapabilitiesResponse, error) {
	out := new(GetAudioCapabilitiesResponse)
	err := c.cc.Invoke(ctx, AudioService_GetAudioCapabilities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility
type AudioServiceServer interface {
	StreamAudioIn(AudioService_StreamAudioInServer) error
	StreamAudioOut(*StreamAudioOutRequest, AudioService_StreamAudioOutServer) error
	InterruptTTS(context.Context, *InterruptTTSRequest) (*emptypb.Empty, error)
	GetAudioCapabilities(context.Context, *GetAudioCapabilitiesRequest) (*GetAudioCapabilitiesResponse, error)
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAudioServiceServer struct {
}

func (UnimplementedAudioServiceServer) StreamAudioIn(AudioService_StreamAudioInServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudioIn not implemented")
}
func (UnimplementedAudioServiceServer) StreamAudioOut(*StreamAudioOutRequest, AudioService_StreamAudioOutServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudioOut not implemented")
}
func (UnimplementedAudioServiceServer) InterruptTTS(context.Context, *InterruptTTSRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterruptTTS not implemented")
}
func (UnimplementedAudioServiceServer) GetAudioCapabilities(context.Context, *GetAudioCapabilitiesRequest) (*GetAudioCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioCapabilities not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_StreamAudioIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioServiceServer).StreamAudioIn(&audioServiceStreamAudioInServer{stream})
}

type AudioService_StreamAudioInServer interface {
	SendAndClose(*StreamAudioInResponse) error
	Recv() (*StreamAudioInRequest, error)
	grpc.ServerStream
}

type audioServiceStreamAudioInServer struct {
	grpc.ServerStream
}

func (x *audioServiceStreamAudioInServer) SendAndClose(m *StreamAudioInResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *audioServiceStreamAudioInServer) Recv() (*StreamAudioInRequest, error) {
	m := new(StreamAudioInRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AudioService_StreamAudioOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAudioOutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).StreamAudioOut(m, &audioServiceStreamAudioOutServer{stream})
}

type AudioService_StreamAudioOutServer interface {
	Send(*StreamAudioOutResponse) error
	grpc.ServerStream
}

type audioServiceStreamAudioOutServer struct {
	grpc.ServerStream
}

func (x *audioServiceStreamAudioOutServer) Send(m *StreamAudioOutResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AudioService_InterruptTTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptTTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).InterruptTTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_InterruptTTS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).InterruptTTS(ctx, req.(*InterruptTTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_GetAudioCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).GetAudioCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_GetAudioCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).GetAudioCapabilities(ctx, req.(*GetAudioCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InterruptTTS",
			Handler:    _AudioService_InterruptTTS_Handler,
		},
		{
			MethodName: "GetAudioCapabilities",
			Handler:    _AudioService_GetAudioCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudioIn",
			Handler:       _AudioService_StreamAudioIn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAudioOut",
			Handler:       _AudioService_StreamAudioOut_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nupi.proto",
}

const (
	AuthService_ListTokens_FullMethodName    = "/nupi.api.v1.AuthService/ListTokens"
	AuthService_CreateToken_FullMethodName   = "/nupi.api.v1.AuthService/CreateToken"
	AuthService_DeleteToken_FullMethodName   = "/nupi.api.v1.AuthService/DeleteToken"
	AuthService_ListPairings_FullMethodName  = "/nupi.api.v1.AuthService/ListPairings"
	AuthService_CreatePairing_FullMethodName = "/nupi.api.v1.AuthService/CreatePairing"
	AuthService_ClaimPairing_FullMethodName  = "/nupi.api.v1.AuthService/ClaimPairing"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
	CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*CreateTokenResponse, error)
	DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPairings(ctx context.Context, in *ListPairingsRequest, opts ...grpc.CallOption) (*ListPairingsResponse, error)
	CreatePairing(ctx context.Context, in *CreatePairingRequest, opts ...grpc.CallOption) (*CreatePairingResponse, error)
	ClaimPairing(ctx context.Context, in *ClaimPairingRequest, opts ...grpc.CallOption) (*ClaimPairingResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	out := new(ListTokensResponse)
	err := c.cc.Invoke(ctx, AuthService_ListTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*CreateTokenResponse, error) {
	out := new(CreateTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_DeleteToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListPairings(ctx context.Context, in *ListPairingsRequest, opts ...grpc.CallOption) (*ListPairingsResponse, error) {
	out := new(ListPairingsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListPairings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreatePairing(ctx context.Context, in *CreatePairingRequest, opts ...grpc.CallOption) (*CreatePairingResponse, error) {
	out := new(CreatePairingResponse)
	err := c.cc.Invoke(ctx, AuthService_CreatePairing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ClaimPairing(ctx context.Context, in *ClaimPairingRequest, opts ...grpc.CallOption) (*ClaimPairingResponse, error) {
	out := new(ClaimPairingResponse)
	err := c.cc.Invoke(ctx, AuthService_ClaimPairing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error)
	CreateToken(context.Context, *CreateTokenRequest) (*CreateTokenResponse, error)
	DeleteToken(context.Context, *DeleteTokenRequest) (*emptypb.Empty, error)
	ListPairings(context.Context, *ListPairingsRequest) (*ListPairingsResponse, error)
	CreatePairing(context.Context, *CreatePairingRequest) (*CreatePairingResponse, error)
	ClaimPairing(context.Context, *ClaimPairingRequest) (*ClaimPairingResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTokens not implemented")
}
func (UnimplementedAuthServiceServer) CreateToken(context.Context, *CreateTokenRequest) (*CreateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedAuthServiceServer) DeleteToken(context.Context, *DeleteTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToken not implemented")
}
func (UnimplementedAuthServiceServer) ListPairings(context.Context, *ListPairingsRequest) (*ListPairingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPairings not implemented")
}
func (UnimplementedAuthServiceServer) CreatePairing(context.Context, *CreatePairingRequest) (*CreatePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePairing not implemented")
}
func (UnimplementedAuthServiceServer) ClaimPairing(context.Context, *ClaimPairingRequest) (*ClaimPairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimPairing not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListTokens(ctx, req.(*ListTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateToken(ctx, req.(*CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteToken(ctx, req.(*DeleteTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListPairings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPairingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListPairings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListPairings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListPairings(ctx, req.(*ListPairingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreatePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreatePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreatePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreatePairing(ctx, req.(*CreatePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ClaimPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ClaimPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ClaimPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ClaimPairing(ctx, req.(*ClaimPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTokens",
			Handler:    _AuthService_ListTokens_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _AuthService_CreateToken_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _AuthService_DeleteToken_Handler,
		},
		{
			MethodName: "ListPairings",
			Handler:    _AuthService_ListPairings_Handler,
		},
		{
			MethodName: "CreatePairing",
			Handler:    _AuthService_CreatePairing_Handler,
		},
		{
			MethodName: "ClaimPairing",
			Handler:    _AuthService_ClaimPairing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nupi.proto",
}

const (
	RecordingsService_ListRecordings_FullMethodName = "/nupi.api.v1.RecordingsService/ListRecordings"
	RecordingsService_GetRecording_FullMethodName   = "/nupi.api.v1.RecordingsService/GetRecording"
)

// RecordingsServiceClient is the client API for RecordingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordingsServiceClient interface {
	ListRecordings(ctx context.Context, in *ListRecordingsRequest, opts ...grpc.CallOption) (*ListRecordingsResponse, error)
	GetRecording(ctx context.Context, in *GetRecordingRequest, opts ...grpc.CallOption) (RecordingsService_GetRecordingClient, error)
}

type recordingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingsServiceClient(cc grpc.ClientConnInterface) RecordingsServiceClient {
	return &recordingsServiceClient{cc}
}

func (c *recordingsServiceClient) ListRecordings(ctx context.Context, in *ListRecordingsRequest, opts ...grpc.CallOption) (*ListRecordingsResponse, error) {
	out := new(ListRecordingsResponse)
	err := c.cc.Invoke(ctx, RecordingsService_ListRecordings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingsServiceClient) GetRecording(ctx context.Context, in *GetRecordingRequest, opts ...grpc.CallOption) (RecordingsService_GetRecordingClient, error) {
	stream, err := c.cc.NewStream(ctx, &RecordingsService_ServiceDesc.Streams[0], RecordingsService_GetRecording_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recordingsServiceGetRecordingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecordingsService_GetRecordingClient interface {
	Recv() (*RecordingChunk, error)
	grpc.ClientStream
}

type recordingsServiceGetRecordingClient struct {
	grpc.ClientStream
}

func (x *recordingsServiceGetRecordingClient) Recv() (*RecordingChunk, error) {
	m := new(RecordingChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecordingsServiceServer is the server API for RecordingsService service.
// All implementations must embed UnimplementedRecordingsServiceServer
// for forward compatibility
type RecordingsServiceServer interface {
	ListRecordings(context.Context, *ListRecordingsRequest) (*ListRecordingsResponse, error)
	GetRecording(*GetRecordingRequest, RecordingsService_GetRecordingServer) error
	mustEmbedUnimplementedRecordingsServiceServer()
}

// UnimplementedRecordingsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRecordingsServiceServer struct {
}

func (UnimplementedRecordingsServiceServer) ListRecordings(context.Context, *ListRecordingsRequest) (*ListRecordingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecordings not implemented")
}
func (UnimplementedRecordingsServiceServer) GetRecording(*GetRecordingRequest, RecordingsService_GetRecordingServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRecording not implemented")
}
func (UnimplementedRecordingsServiceServer) mustEmbedUnimplementedRecordingsServiceServer() {}

// UnsafeRecordingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingsServiceServer will
// result in compilation errors.
type UnsafeRecordingsServiceServer interface {
	mustEmbedUnimplementedRecordingsServiceServer()
}

func RegisterRecordingsServiceServer(s grpc.ServiceRegistrar, srv RecordingsServiceServer) {
	s.RegisterService(&RecordingsService_ServiceDesc, srv)
}

func _RecordingsService_ListRecordings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingsServiceServer).ListRecordings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingsService_ListRecordings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingsServiceServer).ListRecordings(ctx, req.(*ListRecordingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingsService_GetRecording_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecordingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordingsServiceServer).GetRecording(m, &recordingsServiceGetRecordingServer{stream})
}

type RecordingsService_GetRecordingServer interface {
	Send(*RecordingChunk) error
	grpc.ServerStream
}

type recordingsServiceGetRecordingServer struct {
	grpc.ServerStream
}

func (x *recordingsServiceGetRecordingServer) Send(m *RecordingChunk) error {
	return x.ServerStream.SendMsg(m)
}

// RecordingsService_ServiceDesc is the grpc.ServiceDesc for RecordingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.RecordingsService",
	HandlerType: (*RecordingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRecordings",
			Handler:    _RecordingsService_ListRecordings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRecording",
			Handler:       _RecordingsService_GetRecording_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nupi.proto",
}

const (
	ConfigService_GetTransportConfig_FullMethodName    = "/nupi.api.v1.ConfigService/GetTransportConfig"
	ConfigService_UpdateTransportConfig_FullMethodName = "/nupi.api.v1.ConfigService/UpdateTransportConfig"
	ConfigService_Migrate_FullMethodName               = "/nupi.api.v1.ConfigService/Migrate"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	GetTransportConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransportConfig, error)
	UpdateTransportConfig(ctx context.Context, in *UpdateTransportConfigRequest, opts ...grpc.CallOption) (*TransportConfig, error)
	Migrate(ctx context.Context, in *ConfigMigrateRequest, opts ...grpc.CallOption) (*ConfigMigrateResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetTransportConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransportConfig, error) {
	out := new(TransportConfig)
	err := c.cc.Invoke(ctx, ConfigService_GetTransportConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateTransportConfig(ctx context.Context, in *UpdateTransportConfigRequest, opts ...grpc.CallOption) (*TransportConfig, error) {
	out := new(TransportConfig)
	err := c.cc.Invoke(ctx, ConfigService_UpdateTransportConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Migrate(ctx context.Context, in *ConfigMigrateRequest, opts ...grpc.CallOption) (*ConfigMigrateResponse, error) {
	out := new(ConfigMigrateResponse)
	err := c.cc.Invoke(ctx, ConfigService_Migrate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	GetTransportConfig(context.Context, *emptypb.Empty) (*TransportConfig, error)
	UpdateTransportConfig(context.Context, *UpdateTransportConfigRequest) (*TransportConfig, error)
	Migrate(context.Context, *ConfigMigrateRequest) (*ConfigMigrateResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) GetTransportConfig(context.Context, *emptypb.Empty) (*TransportConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransportConfig not implemented")
}
func (UnimplementedConfigServiceServer) UpdateTransportConfig(context.Context, *UpdateTransportConfigRequest) (*TransportConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransportConfig not implemented")
}
func (UnimplementedConfigServiceServer) Migrate(context.Context, *ConfigMigrateRequest) (*ConfigMigrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetTransportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetTransportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetTransportConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetTransportConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateTransportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransportConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateTransportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_UpdateTransportConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateTransportConfig(ctx, req.(*UpdateTransportConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Migrate(ctx, req.(*ConfigMigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransportConfig",
			Handler:    _ConfigService_GetTransportConfig_Handler,
		},
		{
			MethodName: "UpdateTransportConfig",
			Handler:    _ConfigService_UpdateTransportConfig_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _ConfigService_Migrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nupi.proto",
}

const (
	AdaptersService_ListAdapters_FullMethodName        = "/nupi.api.v1.AdaptersService/ListAdapters"
	AdaptersService_ListAdapterBindings_FullMethodName = "/nupi.api.v1.AdaptersService/ListAdapterBindings"
	AdaptersService_SetAdapterBinding_FullMethodName   = "/nupi.api.v1.AdaptersService/SetAdapterBinding"
	AdaptersService_ClearAdapterBinding_FullMethodName = "/nupi.api.v1.AdaptersService/ClearAdapterBinding"
)

// AdaptersServiceClient is the client API for AdaptersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdaptersServiceClient interface {
	ListAdapters(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAdaptersResponse, error)
	ListAdapterBindings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAdapterBindingsResponse, error)
	SetAdapterBinding(ctx context.Context, in *SetAdapterBindingRequest, opts ...grpc.CallOption) (*AdapterBinding, error)
	ClearAdapterBinding(ctx context.Context, in *ClearAdapterBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adaptersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdaptersServiceClient(cc grpc.ClientConnInterface) AdaptersServiceClient {
	return &adaptersServiceClient{cc}
}

func (c *adaptersServiceClient) ListAdapters(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAdaptersResponse, error) {
	out := new(ListAdaptersResponse)
	err := c.cc.Invoke(ctx, AdaptersService_ListAdapters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adaptersServiceClient) ListAdapterBindings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAdapterBindingsResponse, error) {
	out := new(ListAdapterBindingsResponse)
	err := c.cc.Invoke(ctx, AdaptersService_ListAdapterBindings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adaptersServiceClient) SetAdapterBinding(ctx context.Context, in *SetAdapterBindingRequest, opts ...grpc.CallOption) (*AdapterBinding, error) {
	out := new(AdapterBinding)
	err := c.cc.Invoke(ctx, AdaptersService_SetAdapterBinding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adaptersServiceClient) ClearAdapterBinding(ctx context.Context, in *ClearAdapterBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdaptersService_ClearAdapterBinding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdaptersServiceServer is the server API for AdaptersService service.
// All implementations must embed UnimplementedAdaptersServiceServer
// for forward compatibility
type AdaptersServiceServer interface {
	ListAdapters(context.Context, *emptypb.Empty) (*ListAdaptersResponse, error)
	ListAdapterBindings(context.Context, *emptypb.Empty) (*ListAdapterBindingsResponse, error)
	SetAdapterBinding(context.Context, *SetAdapterBindingRequest) (*AdapterBinding, error)
	ClearAdapterBinding(context.Context, *ClearAdapterBindingRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAdaptersServiceServer()
}

// UnimplementedAdaptersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdaptersServiceServer struct {
}

func (UnimplementedAdaptersServiceServer) ListAdapters(context.Context, *emptypb.Empty) (*ListAdaptersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdapters not implemented")
}
func (UnimplementedAdaptersServiceServer) ListAdapterBindings(context.Context, *emptypb.Empty) (*ListAdapterBindingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdapterBindings not implemented")
}
func (UnimplementedAdaptersServiceServer) SetAdapterBinding(context.Context, *SetAdapterBindingRequest) (*AdapterBinding, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAdapterBinding not implemented")
}
func (UnimplementedAdaptersServiceServer) ClearAdapterBinding(context.Context, *ClearAdapterBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearAdapterBinding not implemented")
}
func (UnimplementedAdaptersServiceServer) mustEmbedUnimplementedAdaptersServiceServer() {}

// UnsafeAdaptersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdaptersServiceServer will
// result in compilation errors.
type UnsafeAdaptersServiceServer interface {
	mustEmbedUnimplementedAdaptersServiceServer()
}

func RegisterAdaptersServiceServer(s grpc.ServiceRegistrar, srv AdaptersServiceServer) {
	s.RegisterService(&AdaptersService_ServiceDesc, srv)
}

func _AdaptersService_ListAdapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdaptersServiceServer).ListAdapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdaptersService_ListAdapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdaptersServiceServer).ListAdapters(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdaptersService_ListAdapterBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdaptersServiceServer).ListAdapterBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdaptersService_ListAdapterBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdaptersServiceServer).ListAdapterBindings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdaptersService_SetAdapterBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdapterBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdaptersServiceServer).SetAdapterBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdaptersService_SetAdapterBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdaptersServiceServer).SetAdapterBinding(ctx, req.(*SetAdapterBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdaptersService_ClearAdapterBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAdapterBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdaptersServiceServer).ClearAdapterBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdaptersService_ClearAdapterBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdaptersServiceServer).ClearAdapterBinding(ctx, req.(*ClearAdapterBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdaptersService_ServiceDesc is the grpc.ServiceDesc for AdaptersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdaptersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.AdaptersService",
	HandlerType: (*AdaptersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAdapters",
			Handler:    _AdaptersService_ListAdapters_Handler,
		},
		{
			MethodName: "ListAdapterBindings",
			Handler:    _AdaptersService_ListAdapterBindings_Handler,
		},
		{
			MethodName: "SetAdapterBinding",
			Handler:    _AdaptersService_SetAdapterBinding_Handler,
		},
		{
			MethodName: "ClearAdapterBinding",
			Handler:    _AdaptersService_ClearAdapterBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nupi.proto",
}

const (
	QuickstartService_GetStatus_FullMethodName = "/nupi.api.v1.QuickstartService/GetStatus"
	QuickstartService_Update_FullMethodName    = "/nupi.api.v1.QuickstartService/Update"
)

// QuickstartServiceClient is the client API for QuickstartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuickstartServiceClient interface {
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QuickstartStatusResponse, error)
	Update(ctx context.Context, in *UpdateQuickstartRequest, opts ...grpc.CallOption) (*QuickstartStatusResponse, error)
}

type quickstartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuickstartServiceClient(cc grpc.ClientConnInterface) QuickstartServiceClient {
	return &quickstartServiceClient{cc}
}

func (c *quickstartServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QuickstartStatusResponse, error) {
	out := new(QuickstartStatusResponse)
	err := c.cc.Invoke(ctx, QuickstartService_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickstartServiceClient) Update(ctx context.Context, in *UpdateQuickstartRequest, opts ...grpc.CallOption) (*QuickstartStatusResponse, error) {
	out := new(QuickstartStatusResponse)
	err := c.cc.Invoke(ctx, QuickstartService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuickstartServiceServer is the server API for QuickstartService service.
// All implementations must embed UnimplementedQuickstartServiceServer
// for forward compatibility
type QuickstartServiceServer interface {
	GetStatus(context.Context, *emptypb.Empty) (*QuickstartStatusResponse, error)
	Update(context.Context, *UpdateQuickstartRequest) (*QuickstartStatusResponse, error)
	mustEmbedUnimplementedQuickstartServiceServer()
}

// UnimplementedQuickstartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuickstartServiceServer struct {
}

func (UnimplementedQuickstartServiceServer) GetStatus(context.Context, *emptypb.Empty) (*QuickstartStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedQuickstartServiceServer) Update(context.Context, *UpdateQuickstartRequest) (*QuickstartStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedQuickstartServiceServer) mustEmbedUnimplementedQuickstartServiceServer() {}

// UnsafeQuickstartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuickstartServiceServer will
// result in compilation errors.
type UnsafeQuickstartServiceServer interface {
	mustEmbedUnimplementedQuickstartServiceServer()
}

func RegisterQuickstartServiceServer(s grpc.ServiceRegistrar, srv QuickstartServiceServer) {
	s.RegisterService(&QuickstartService_ServiceDesc, srv)
}

func _QuickstartService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickstartServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuickstartService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickstartServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuickstartService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuickstartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickstartServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuickstartService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickstartServiceServer).Update(ctx, req.(*UpdateQuickstartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuickstartService_ServiceDesc is the grpc.ServiceDesc for QuickstartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuickstartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nupi.api.v1.QuickstartService",
	HandlerType: (*QuickstartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _QuickstartService_GetStatus_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _QuickstartService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nupi.proto",
}
